version: '3.5'

networks:
    application:
        name: application
        external: true

services:
  db:
    image: "mysql:5.7"
    container_name: mysql-5-7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: servicedb
    ports:
      - "3306:3306"
    networks:
      - application
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - application
  php:
    image: bref/php-81-fpm-dev
    container_name: php-8.1.15
    ports:
      - 8081:8000
    links:
      - "db"
    environment:
        HANDLER: public/index.php
        DOCUMENT_ROOT: public
    volumes:
      - .:/var/task:ro
    networks:
      - application